AccountsManagement/Controllers/AccountsController.cs
using AccountsManagement.DAL.Interface;
using AccountsManagement.Models.ViewModel;
using PagedList;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCAssessment.Controllers
{
    public class AccountsController : Controller
    {
        #region Constructor
        private IDataAccess _dataAccess { get; set; }

        public AccountsController(IDataAccess dataAccess)
        {
            _dataAccess = dataAccess;
        }
        #endregion

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateAccount(AccountsViewModel account)
        {
            if (ModelState.IsValid)
            {                
                Tuple<bool, string> results = _dataAccess.SaveAccount(account);
                return Json(new { Success = results.Item1, Message = results.Item2 }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { Success = false, Message = "Invalid Account object." }, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public JsonResult CloseAccount(AccountsViewModel account)
        {
            if (ModelState.IsValid)
            {                
                Tuple<bool, string> results = _dataAccess.CloseAccount(account.code);
                return Json(new { Success = results.Item1, Message = results.Item2 }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { Success = false, Message = "Invalid Account object." }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ReOpenAccount(AccountsViewModel account)
        {
            if (ModelState.IsValid)
            {
                Tuple<bool, string> results = _dataAccess.ReOpenAccount(account.code);
                return Json(new { Success = results.Item1, Message = results.Item2 }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { Success = false, Message = "Invalid Account object." }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddAccount(PersonAccountsViewModel account)
        {
            if (account.Account != null)
            {
                int itemNo = account.Accounts.Count;
                Tuple<bool, string> results = _dataAccess.SaveAccount(account.Account);
                ViewBag.Message = results.Item2;
            }

            return PartialView("Edit","Persons");
        }

        [HttpPost]
        public ActionResult Edit(AccountsViewModel model, string action, int code, int? pageNumber)
        {            
            if(action.ToLower() == "edit")
            {         
                AccountsViewModel account = _dataAccess.GetAllAccounts().Where(x => x.code == code).FirstOrDefault();

                AccountTransactionsViewModel viewModel = new AccountTransactionsViewModel
                {
                    Account = account,
                    Transaction = new TransactionsViewModel { account_code = account.code, transaction_date = DateTime.Now},
                    Transactions = _dataAccess.GetTransactionsByAccountCode(code).ToList()
                };

                return View("Edit", viewModel);        

            }

            var data = _dataAccess.GetAllAccounts().ToPagedList(pageNumber ?? 1, 10);
            return View("Index", data);
        }

        [HttpPost]
        public JsonResult UpdateAccount(AccountsViewModel account)
        {
            if (ModelState.IsValid)
            {
                Tuple<bool, string> results = _dataAccess.UpdateAccount(account);
                return Json(new { Success = results.Item1, Message = results.Item2 }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { Success = false, Message = "Invalid Person object." }, JsonRequestBehavior.AllowGet);
        }
    }
}

AccountsManagement/Controllers/TransactionsController.cs
using AccountsManagement.DAL.Interface;
using AccountsManagement.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCAssessment.Controllers
{
    public class TransactionsController : Controller
    {
        #region Constructor
        private IDataAccess _dataAccess { get; set; }

        public TransactionsController(IDataAccess dataAccess)
        {
            _dataAccess = dataAccess;
        }
        #endregion

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateTransaction(TransactionsViewModel transaction)
        {
            if (ModelState.IsValid)
            {                
                Tuple<bool, string> results = _dataAccess.SaveTransaction(transaction);
                return Json(new { Success = results.Item1, Message = results.Item2 }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { Success = false, Message = "Invalid Transaction object." }, JsonRequestBehavior.AllowGet);
        }
   
        public JsonResult UpdateTransaction(TransactionsViewModel transaction)
        {
            if (ModelState.IsValid)
            {
                Tuple<bool, string> results = _dataAccess.UpdateTransaction(transaction);
                return Json(new { Success = results.Item1, Message = results.Item2 }, JsonRequestBehavior.AllowGet);
            } 

            return Json(new { Success = false, Message = "Invalid Transaction object." }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Edit(int code)
        {
             TransactionsViewModel transaction = _dataAccess.GetAllTransactions().Where(x => x.code == code).FirstOrDefault();
             return View(transaction);
        }
    }
}

AccountsManagement/Views/Accounts/Edit.cshtml
@using AccountsManagement.Models.ViewModel;
@model AccountsManagement.Models.ViewModel.AccountTransactionsViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";    
}

<h2>Account Transactions information</h2>

<div class="container">

    <div>
        <h4>Account details</h4>
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Account.person_code)
            @Html.HiddenFor(model => model.Account.code)
            <div class="form-group">
                @Html.LabelFor(model => model.Account.account_number, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">                    
                    <input type="text" id="accountnumber" name="Account.accountnumber" value="@Model.Account.account_number" class="form-control" />
                    <span class="error"><b>Please provide a valid account number!</b></span>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Account.outstanding_balance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Account.outstanding_balance, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Account.account_active, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.HiddenFor(model => model.Account.account_active)
                <div class="col-md-10">
                    @if (@Model.Account.account_active)
                    {                        
                        <input type="checkbox" id="accountactive" name="Account.account_active" readonly="readonly" value="1" class="form-control" checked/>                        
                    }
                    else
                    {
                        <input type="checkbox" id="accountactive" name="Account.account_active" disabled="disabled" readonly="readonly" value="0" class="form-control" unchecked/>                        
                    }
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">                    
                    <button type="submit" name="action" value="Update" class="btn btn-primary a-btn-slide-text" onclick="UpdateAccount('@Model.Account.code')">
                        <span class="glyphicon glyphicon-cloud-upload" aria-hidden="true"></span><strong> Update</strong>
                    </button>
                    @if (!@Model.Account.account_active)
                    {
                        <button name="action" value="close" class="btn btn-primary a-btn-slide-text" onclick="ReOpenAccount('@Model.Account.code')">
                            <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span><strong> Re-Open</strong>
                        </button>
                    }
                </div>
            </div>
        </div>
        @*}*@
    </div>

    <h4>New Transcation</h4>

    <div class="row well">
        <button type="button" id="create" class="btn btn-info pull-right" data-toggle="modal" data-target="#createtransactionModal">
            <i class="glyphicon glyphicon-plus">
            </i> Create Transaction
        </button>
    </div>

    <div id="createtransactionModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h2 class="modal-title">New Transaction</h2>
                </div>
                <div class="modal-body">
                    <h4>Transaction Information</h4>
                    <table class="table table-responsive">
                        <tr>
                            <td>Capture Date</td>
                            <td>
                                @Html.EditorFor(model => model.Transaction.capture_date, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })                               
                            </td>
                        </tr>
                        <tr>
                            <td>Transaction Date</td>
                            <td>
                                <input type="date" id="transactiondate" class="form-control" />
                                <span class="error"><b>Please provide a valid transaction date-not greater than today!</b></span>
                            </td>
                        </tr>
                        <tr>
                            <td>Transaction Type</td>
                            <td>
                                <select id="transactiontype" name="transactiontypes" class="form-control" >
                                    <option value="C">Credit</option>
                                    <option value="D">Debit</option>                                    
                                </select>                                                                
                            </td>
                        </tr>
                        <tr>
                            <td>Transaction Amount</td>
                            <td>
                                <input type="text" id="amount" class="form-control" />
                                <span class="error"><b>Please provide a valid amount, greater than zero!</b></span>
                            </td>
                        </tr>
                        <tr>
                            <td>Description</td>
                            <td>
                                <input type="text" id="description" class="form-control" />
                                <span class="error"><b>Please provide a valid description!</b></span>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" onclick="CreateTransaction('@Model.Account.code','@Model.Transaction.capture_date')" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
     
    <div>
        <p><b>Transactions List</b></p>
        <table class="table table-responsive">
            <tr>
                <th>Transaction Date</th>
                <th>Capture Date</th>
                <th>Amount</th>
                <th>Description</th>
            </tr>
            @foreach (TransactionsViewModel transaction in Model.Transactions)
            {
                <tr class="mycontainer" id="mainrow">
                    <td>@transaction.transaction_date</td>
                    <td>@transaction.capture_date</td>
                    <td>@transaction.amount</td>
                    <td>@transaction.description</td>
                    <td>
                        @using (Html.BeginForm("Edit", "Transactions", new { code = transaction.code }, FormMethod.Post))
                        {
                            <button name="action" value="edit" class="btn btn-primary a-btn-slide-text">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><strong>Edit</strong>
                            </button>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>

    <div>
        @using (Html.BeginForm("Edit", "Persons", new { code = Model.Account.person_code }, FormMethod.Post))
        {
            <button name="action" value="edit" class="btn btn-primary">GO BACK</button>
        }
        @*<input type="button" value="GO BACK" class="btn btn-primary"
        onclick="location.href='@Request.UrlReferrer'" />*@
       
    </div>
</div>

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/moment.js"></script>
<script src="~/Scripts/toastr.js"></script>
<script src="~/Scripts/myScripts.js?v=6"></script>
<link href="~/Content/toastr.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

<script type="text/javascript">
    
    function CreateTransaction(accountCode, captureDate) {

        if (!ValidateTransaction())
            return;

        var accountData =
        {
            account_code: accountCode,
            transaction_date: $('#transactiondate').val(),
            capture_date: captureDate,
            amount: $('#amount').val(),
            description: $('#description').val().trim(),
            transaction_type: $('#transactiontype').val()
        }

        $.ajax({
            type: "POST",
            url: '/Transactions/CreateTransaction',
            data: accountData,
            success: function (result) {
                if (result.Success == true) {                   
                    toastr.success(result.Message);
                    setInterval('location.reload()', 3000);
                }
                else {
                    toastr.error(result.Message);
                }
            },
            error: function (xhr, error) {
                toastr.error("An error occured while trying to create transaction. Status: " + xhr.status + ", Error: " + xhr.statusText);
            }
        });
    }

    function ReOpenAccount(accountCode) {
        var accountData =
        {
            code: accountCode
        }

        $.ajax({
            type: "POST",
            url: '/Accounts/ReOpenAccount',@* '@Url.Action("ReOpenAccount", "Accounts")',*@
            data: accountData,
            success: function (result) {
                if (result.Success == true) {
                    toastr.success(result.Message);
                    setInterval('location.reload()', 3000);
                }
                else {
                    toastr.error(result.Message);
                }

            },
            error: function (xhr, error) {
                toastr.error("An error occured while trying to re-open account. Status: " + xhr.status + ", Error: " + xhr.statusText);
            }
        });
    }
</script>

AccountsManagement/Views/Accounts/Index.cshtml
@model IEnumerable<AccountsManagement.DAL.Account>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.account_number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.outstanding_balance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.account_active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Person.name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.account_number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.outstanding_balance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.account_active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Person.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.code }) |
            @Html.ActionLink("Details", "Details", new { id=item.code }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.code })
        </td>
    </tr>
}

</table>